name: Publish Python package to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: "3.12"

      - name: 🔧 Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: 📦 Build sdist and wheel
        run: |
          python -m build
          ls -l dist

      - name: 🔐 Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload dist/*